### ISSUE TITLE
Separatore decimale dell'esportazione del file CSV

### ISSUE THREAD

**Issue by Simo75** [vaniacarta74/scarichi#5]
Sarebbe opportuno che per impostazione predefinita il VALORE nel file di esportazione CSV avesse la virgola come separatore decimale, altrimenti nel pacchetto Microsoft Office impostato secondo le nostre impostazioni locali si perderanno tutti i decimali (venendo convertito in numero intero).

**Comment by vaniacarta74** [comment]
Tutti i dati numerici, prima dell'esportazione in CSV ora vengono trasformati in stringa formattata. In particolare:
- Gli interi con format_number($valore, 0, '', '')
- I float con format_number($valore, 3, ',', '')
